# Generated by Django 4.1 on 2022-11-29 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxLengthValidator(100)])),
                ('drone_model', models.CharField(choices=[('Cruiseweight', 'Cruiseweight'), ('Lightweight', 'Lightweight'), ('Middleweight', 'Middleweight'), ('Heavyweight', 'Heavyweight')], max_length=25)),
                ('weight_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('battery_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sate', models.CharField(choices=[('LOADING', 'LOADING'), ('DELIVERED', 'DELIVERED'), ('RETURNING', 'RETURNING'), ('LOADED', 'LOADED'), ('DELIVERING', 'DELIVERING'), ('IDLE', 'IDLE')], max_length=25)),
            ],
            options={
                'verbose_name': 'Drone',
                'verbose_name_plural': 'Drones',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('code', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
            },
        ),
    ]
