# Generated by Django 4.1 on 2022-11-29 18:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='load',
            field=models.ForeignKey(blank=True, db_column='id_medication', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.medication', verbose_name='Medication'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='drone_model',
            field=models.CharField(choices=[('Middleweight', 'Middleweight'), ('Cruiseweight', 'Cruiseweight'), ('Heavyweight', 'Heavyweight'), ('Lightweight', 'Lightweight')], max_length=25),
        ),
        migrations.AlterField(
            model_name='drone',
            name='sate',
            field=models.CharField(choices=[('LOADED', 'LOADED'), ('RETURNING', 'RETURNING'), ('LOADING', 'LOADING'), ('IDLE', 'IDLE'), ('DELIVERED', 'DELIVERED'), ('DELIVERING', 'DELIVERING')], max_length=25),
        ),
        migrations.AlterField(
            model_name='drone',
            name='serial_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
