# Generated by Django 4.1 on 2022-11-29 19:10

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_drone_load_alter_drone_drone_model_alter_drone_sate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='load',
        ),
        migrations.AlterField(
            model_name='drone',
            name='drone_model',
            field=models.CharField(choices=[('Lightweight', 'Lightweight'), ('Middleweight', 'Middleweight'), ('Heavyweight', 'Heavyweight'), ('Cruiseweight', 'Cruiseweight')], max_length=25),
        ),
        migrations.AlterField(
            model_name='drone',
            name='sate',
            field=models.CharField(choices=[('DELIVERING', 'DELIVERING'), ('IDLE', 'IDLE'), ('LOADED', 'LOADED'), ('RETURNING', 'RETURNING'), ('DELIVERED', 'DELIVERED'), ('LOADING', 'LOADING')], max_length=25),
        ),
        migrations.AlterField(
            model_name='medication',
            name='image',
            field=models.ImageField(upload_to=main.models.upload_to_medication),
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone', models.ForeignKey(blank=True, db_column='id_drone', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='drone', to='main.drone', verbose_name='Drone')),
                ('medication', models.ForeignKey(blank=True, db_column='id_medication', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medication', to='main.medication', verbose_name='Medication')),
            ],
        ),
    ]
