# Generated by Django 4.1 on 2022-11-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_drone_load_alter_drone_drone_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='drone_model',
            field=models.CharField(choices=[('Cruiseweight', 'Cruiseweight'), ('Heavyweight', 'Heavyweight'), ('Middleweight', 'Middleweight'), ('Lightweight', 'Lightweight')], max_length=25),
        ),
        migrations.AlterField(
            model_name='drone',
            name='sate',
            field=models.CharField(choices=[('RETURNING', 'RETURNING'), ('DELIVERING', 'DELIVERING'), ('LOADED', 'LOADED'), ('LOADING', 'LOADING'), ('IDLE', 'IDLE'), ('DELIVERED', 'DELIVERED')], max_length=25),
        ),
        migrations.DeleteModel(
            name='Load',
        ),
    ]
