# Generated by Django 4.1 on 2022-11-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_drone_drone_model_alter_drone_sate_delete_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='load',
            field=models.ManyToManyField(to='main.medication'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='drone_model',
            field=models.CharField(choices=[('Lightweight', 'Lightweight'), ('Cruiseweight', 'Cruiseweight'), ('Heavyweight', 'Heavyweight'), ('Middleweight', 'Middleweight')], max_length=25),
        ),
        migrations.AlterField(
            model_name='drone',
            name='sate',
            field=models.CharField(choices=[('LOADING', 'LOADING'), ('IDLE', 'IDLE'), ('LOADED', 'LOADED'), ('DELIVERING', 'DELIVERING'), ('DELIVERED', 'DELIVERED'), ('RETURNING', 'RETURNING')], max_length=25),
        ),
    ]
