# Generated by Django 4.1 on 2022-11-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_drone_load_alter_drone_drone_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='sate',
        ),
        migrations.AddField(
            model_name='drone',
            name='state',
            field=models.CharField(choices=[('LOADING', 'LOADING'), ('IDLE', 'IDLE'), ('RETURNING', 'RETURNING'), ('DELIVERED', 'DELIVERED'), ('LOADED', 'LOADED'), ('DELIVERING', 'DELIVERING')], default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drone',
            name='drone_model',
            field=models.CharField(choices=[('Cruiseweight', 'Cruiseweight'), ('Lightweight', 'Lightweight'), ('Heavyweight', 'Heavyweight'), ('Middleweight', 'Middleweight')], max_length=25),
        ),
    ]
