# Generated by Django 4.1 on 2022-12-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_drone_drone_model_alter_drone_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='drone_model',
            field=models.CharField(choices=[('Cruiseweight', 'Cruiseweight'), ('Lightweight', 'Lightweight'), ('Heavyweight', 'Heavyweight'), ('Middleweight', 'Middleweight')], max_length=25),
        ),
        migrations.AlterField(
            model_name='drone',
            name='state',
            field=models.CharField(choices=[('LOADING', 'LOADING'), ('DELIVERED', 'DELIVERED'), ('IDLE', 'IDLE'), ('RETURNING', 'RETURNING'), ('DELIVERING', 'DELIVERING'), ('LOADED', 'LOADED')], max_length=25),
        ),
    ]
