# Generated by Django 4.1 on 2022-12-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_drone_load_alter_drone_drone_model_alter_drone_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='image',
        ),
        migrations.AlterField(
            model_name='drone',
            name='drone_model',
            field=models.CharField(choices=[('Middleweight', 'Middleweight'), ('Lightweight', 'Lightweight'), ('Heavyweight', 'Heavyweight'), ('Cruiseweight', 'Cruiseweight')], max_length=25),
        ),
        migrations.AlterField(
            model_name='drone',
            name='state',
            field=models.CharField(choices=[('RETURNING', 'RETURNING'), ('LOADED', 'LOADED'), ('LOADING', 'LOADING'), ('IDLE', 'IDLE'), ('DELIVERING', 'DELIVERING'), ('DELIVERED', 'DELIVERED')], max_length=25),
        ),
    ]
