# Generated by Django 4.1 on 2022-12-02 04:43

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_medication_image_alter_drone_drone_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.upload_to_medication),
        ),
        migrations.AlterField(
            model_name='drone',
            name='drone_model',
            field=models.CharField(choices=[('Heavyweight', 'Heavyweight'), ('Cruiseweight', 'Cruiseweight'), ('Lightweight', 'Lightweight'), ('Middleweight', 'Middleweight')], max_length=25),
        ),
        migrations.AlterField(
            model_name='drone',
            name='state',
            field=models.CharField(choices=[('LOADED', 'LOADED'), ('RETURNING', 'RETURNING'), ('DELIVERED', 'DELIVERED'), ('LOADING', 'LOADING'), ('IDLE', 'IDLE'), ('DELIVERING', 'DELIVERING')], max_length=25),
        ),
    ]
